[package]
name = "ternyte"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = "symbols" 
debug = false
panic = "abort"

#cargo build --target x86_64-pc-windows-gnu --release
[package.metadata.target.'x86_64-pc-windows-gnu']
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[dependencies]
rel-core = { path = "../rel" }
raylib-sys = "6.0.0"
glam = "0.33.3"

[lints.clippy]
needless_return = "allow"
single_match = "allow"
upper_case_acronyms = "allow"
type_complexity = "allow"
